nickname = "Mike"
STR = 15
DEX = 18
CON = 16
INT = 17
WIS = 12
CHA = 13
BAB = 0
AC = 16
HP = 4
HD = 0
Weapondie = 4
Initiative = 24
Level = 1
Class = "Commoner"
Armor = "Leather Armor"
Weapon = "dagger"
area = "City"
room = "Inn"
position = "22"
PreviousRoom = "Inn"
PreviousArea = "City"
